package org.foedusprogramme.hueflow.palette

import com.google.android.material.R

enum class ColorToken {
    Error,
    ErrorContainer,
    InverseOnSurface,
    InversePrimary,
    OnBackground,
    OnError,
    OnErrorContainer,
    OnPrimary,
    OnPrimaryContainer,
    OnSecondary,
    OnSecondaryContainer,
    OnSurface,
    OnSurfaceVariant,
    OnTertiary,
    OnTertiaryContainer,
    Outline,
    OutlineVariant,
    Primary,
    PrimaryContainer,
    Scrim,
    Secondary,
    SecondaryContainer,
    Surface,
    SurfaceBright,
    SurfaceContainer,
    SurfaceContainerLow,
    SurfaceContainerLowest,
    SurfaceContainerHigh,
    SurfaceContainerHighest,
    SurfaceDim,
    SurfaceVariant,
    Tertiary,
    TertiaryContainer;

    companion object {
        val attrToTokenMapping = mapOf(
            R.attr.colorError to Error,
            R.attr.colorErrorContainer to ErrorContainer,
            R.attr.colorOnSurfaceInverse to InverseOnSurface,
            R.attr.colorPrimaryInverse to InversePrimary,
            R.attr.colorOnBackground to OnBackground,
            R.attr.colorOnError to OnError,
            R.attr.colorOnErrorContainer to OnErrorContainer,
            R.attr.colorOnPrimary to OnPrimary,
            R.attr.colorOnPrimaryContainer to OnPrimaryContainer,
            R.attr.colorOnSecondary to OnSecondary,
            R.attr.colorOnSecondaryContainer to OnSecondaryContainer,
            R.attr.colorOnSurface to OnSurface,
            R.attr.colorOnSurfaceVariant to OnSurfaceVariant,
            R.attr.colorOnTertiary to OnTertiary,
            R.attr.colorOnTertiaryContainer to OnTertiaryContainer,
            R.attr.colorOutline to Outline,
            R.attr.colorOutlineVariant to OutlineVariant,
            R.attr.colorPrimary to Primary,
            R.attr.colorPrimaryContainer to PrimaryContainer,
            R.attr.scrimBackground to Scrim,
            R.attr.colorSecondary to Secondary,
            R.attr.colorSecondaryContainer to SecondaryContainer,
            R.attr.colorSurface to Surface,
            R.attr.colorSurfaceBright to SurfaceBright,
            R.attr.colorSurfaceContainer to SurfaceContainer,
            R.attr.colorSurfaceContainerLow to SurfaceContainerLow,
            R.attr.colorSurfaceContainerLowest to SurfaceContainerLowest,
            R.attr.colorSurfaceContainerHigh to SurfaceContainerHigh,
            R.attr.colorSurfaceContainerHighest to SurfaceContainerHighest,
            R.attr.colorSurfaceDim to SurfaceDim,
            R.attr.colorSurfaceVariant to SurfaceVariant,
            R.attr.colorTertiary to Tertiary,
            R.attr.colorTertiaryContainer to TertiaryContainer,
        )
    }
}
